

replicaCount: 1

image:
  repository: keoffor/kubernize
  pullPolicy: Always

service:
  type: NodePort
  port: 4000
  name: jen-service
  targetPort: 4000

container:
  name: jen-container
resources:
  requests:
    cpu: "250m"
    memory: 250Mi

ingress:
  name: myingress  
  