

replicaCount: 1

image:
  repository: keoffor/kuber-demo
  pullPolicy: Always

service:
  type: NodePort
  port: 4001
  name: jen-service
  targetPort: 4001

container:
  name: jen-container
resources:
  requests:
    cpu: "250m"
    memory: 250Mi

