global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yaml

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['localhost:4003','34.121.114.33:4003']

