---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
  labels:
    app: kuber-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-app
  template:
    metadata:
      labels:
        app: kuber-app
    spec:
      containers:
        - image: keoffor/kuber-demo:%TAG%
          imagePullPolicy: Always
          name: kuber-container
          ports:
            - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuberapi
  name: kuber-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - name: kuber-loader
      port: 4003
      targetPort: 4003
  selector:
    app: kuber-app
