---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-deployment
  labels:
    app: kuber-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuber-app
  template:
    metadata:
      labels:
        app: kuber-app
    spec:
      containers:
        - image: keoffor/kuber-demo:%TAG%
          imagePullPolicy: Always
          name: kuber-container
          ports:
            - containerPort: 4003

---
apiVersion: v1
kind: Service
metadata:
  name: kuber-service
  labels:
    service: kuber-service
spec:
  type: LoadBalancer
  ports:
    - name: http-query
      port: 4003
      targetPort: 4003
  selector:
    app: kuber-app


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kuber-service-monitor
spec:
  selector:
    matchLabels:
      service: kuber-service
  endpoints:
    - port: http-query
      path: "/actuator/prometheus"